// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mJSTe-jXMo8PKikq1hiVx-nq7ajOOSc',
    appId: '1:3772309104:web:50ee70d592a095685ddeb5',
    messagingSenderId: '3772309104',
    projectId: 'ecommerce-dbd52',
    authDomain: 'ecommerce-dbd52.firebaseapp.com',
    storageBucket: 'ecommerce-dbd52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCo2IfgmX6OSGY6UGAZEcahLqqGFPyoiI',
    appId: '1:3772309104:android:0f99e1ea8279259a5ddeb5',
    messagingSenderId: '3772309104',
    projectId: 'ecommerce-dbd52',
    storageBucket: 'ecommerce-dbd52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0soy9JCFxPurJLVqK3GsaOSvC-rDznXQ',
    appId: '1:3772309104:ios:573d2ef5a7d0440a5ddeb5',
    messagingSenderId: '3772309104',
    projectId: 'ecommerce-dbd52',
    storageBucket: 'ecommerce-dbd52.appspot.com',
    iosBundleId: 'com.example.appEcommerce',
  );
}
